use_frameworks!

target 'BeatBallIndicator_Example' do
  pod 'BeatBallIndicator', :path => '../'

  target 'BeatBallIndicator_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
